CREATE TABLE IF NOT EXISTS Todo(id IDENTITY PRIMARY KEY , done BOOLEAN, TEXT VARCHAR(255));
DELETE FROM Todo;
INSERT INTO Todo VALUES(1, true, 'Buy Milk');
INSERT INTO Todo VALUES(2, true, 'Buy Sugar');
INSERT INTO Todo VALUES(3, false, 'Buy Flour');